### ISSUE TITLE
maybe not an issue

### ISSUE THREAD

**Issue by gasparapsag** [MelbourneUniHRL/X-Limb#1]
Hi, 

It's amazing the job that you guys have done with this, I could not find anything similar to this, just amazing! 

I'm trying to build this hand for a cousin who needs it, the thing is when I sent the boom to de PCB manufacturer they said is incomplete as they need the code of the part from mouser or Digikey. I don't know how to correctly choose some of the components as for example for capacitors besides capacitance and footprint voltage is needed to select one and resistor sometimes I can't find the correct footprint.
Here is what I have found so far.
https://drive.google.com/file/d/1TM07XncSh36at8BIBJNJwm0H0ubI7nqd/view?usp=sharing

Could you guys guide me on how to select the rest of the components?

Thank you!

**Comment by MelbourneUniHRL** [comment]
Hi,

We are glad that you found it useful. The PCBs are actually fabricated by contract manufacturer. I can ask them regarding the missing components, probably it will take a bit of time.

If you just need to make one, I have a spare controller which I can post to you at no cost.

Regards,
Alireza


------------------------------------------------------

Alireza Mohammadi
Senior Research Officer,
Department of Mechanical Engineering
The University of Melbourne, Parkville VIC 3010
Phone: +61 3 8345 4378
Email: alirezam@unimelb.edu.au
Webpage: <http://people.eng.unimelb.edu.au/doetomo/> http://people.eng.unimelb.edu.au/alirezam/

________________________________

**Comment by gasparapsag** [comment]
Hi Alireza, 

Such a great news, yes it would be nice if you can post me the controller I will pay the shipping.

Right now I want to make  just one for my cousin, she is a single mother of 4 living in precarious conditions, a few weeks ago she almost took her own life. I wasn’t aware of the psychological problems that amputees have until I got close to one. 
Now you have inspired me to help others too so I will appreciate the full list of components whenever is complete.

Thank you.
Gaspar.

**Comment by MelbourneUniHRL** [comment]
Hi Gaspar,

It is sad to hear that. Just send me your address so I can post it to you.

Her amputation is on her right hand or left hand? Is it below elbow?

I have some other spare parts that can them to you along with the controller.

Regards,
Alireza


------------------------------------------------------

Alireza Mohammadi
Senior Research Officer,
Department of Mechanical Engineering
The University of Melbourne, Parkville VIC 3010
Phone: +61 3 8345 4378
Email: alirezam@unimelb.edu.au
Webpage: <http://people.eng.unimelb.edu.au/doetomo/> http://people.eng.unimelb.edu.au/alirezam/

________________________________

**Comment by gasparapsag** [comment]
Hi Alireza, 

The amputation it’s on her left hand below elbow.
I will send you my address to your email, do you want me to attach a photo of the arm?

Thanks.
Gaspar.

**Comment by MelbourneUniHRL** [comment]
No need for the photo.

Regards,
Alireza


------------------------------------------------------

Alireza Mohammadi
Senior Research Officer,
Department of Mechanical Engineering
The University of Melbourne, Parkville VIC 3010
Phone: +61 3 8345 4378
Email: alirezam@unimelb.edu.au
Webpage: <http://people.eng.unimelb.edu.au/doetomo/> http://people.eng.unimelb.edu.au/alirezam/

________________________________

**Comment by gasparapsag** [comment]
> No need for the photo. Regards, Alireza
> […](#)

Hi Alireza, 

I’ve sent you an email to alirezam@unimelb.edu.au on Tuesday with my personal info, please let me know if you have received it.

Thank you.
Gaspar Catalán.

**Comment by MelbourneUniHRL** [comment]
Yes, I've got you message. I'll send the stuff ASAP.

Regards,
Alireza
________________________________

**Comment by gasparapsag** [comment]
Nice, no worries, just checking in to make sure you received the email.

Thanks.
Gaspar Catalán.

**Comment by MelbourneUniHRL** [comment]
Thanks for your interest. The list has been updated with the link to the parts available in Digikey. The rest of components have been sourced from another company but they are also available in Digikey.

**Comment by gasparapsag** [comment]
Thank you!
